[2025-06-15 12:45:33,283: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-15 12:45:33,305: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-15 12:46:52,238: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-15 12:46:52,249: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-15 12:47:28,070: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-15 12:47:28,071: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-15 12:47:28,080: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-15 12:47:28,088: INFO: common: created directory at: artifacts]
[2025-06-15 12:49:59,112: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-15 12:49:59,112: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-15 12:49:59,112: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-15 12:49:59,112: INFO: common: created directory at: artifacts]
[2025-06-15 12:51:02,567: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-15 12:51:02,574: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-15 12:51:02,578: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-15 12:51:02,579: INFO: common: created directory at: artifacts]
[2025-06-15 12:51:54,664: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-15 12:51:54,668: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-15 12:51:54,668: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-15 12:51:54,668: INFO: common: created directory at: artifacts]
[2025-06-15 12:51:54,674: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-15 12:53:29,949: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-15 12:53:29,949: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-15 12:53:29,954: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-15 12:53:29,955: INFO: common: created directory at: artifacts]
[2025-06-15 12:53:29,956: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-15 12:53:47,289: INFO: 2366278714: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 23329
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "c69888a4ae59bc5a893392785a938ccd4937981c06ba8a9d6a21aa52b4ab5b6e"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: D7B1:13A383:FA23ED:11D2311:684E9828
Accept-Ranges: bytes
Date: Sun, 15 Jun 2025 09:53:46 GMT
Via: 1.1 varnish
X-Served-By: cache-mrs10543-MRS
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1749981226.470164,VS0,VE180
Vary: Authorization,Accept-Encoding
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 00a5da82f51afb54c5b794c72f245e1abd422698
Expires: Sun, 15 Jun 2025 09:58:46 GMT
Source-Age: 0

]
[2025-06-15 12:54:31,329: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-15 12:54:31,331: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-15 12:54:31,331: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-15 12:54:31,337: INFO: common: created directory at: artifacts]
[2025-06-15 12:54:31,339: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-15 12:54:32,908: INFO: 2366278714: artifacts/data_ingestion/data.zip download! with following info: 
Date: Sun, 15 Jun 2025 09:54:31 GMT
Content-Type: text/html; charset=utf-8
Vary: X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, X-Requested-With,Accept-Encoding, Accept, X-Requested-With
x-repository-download: git clone https://github.com/caserec/Datasets-for-Recommender-Systems.git
x-raw-download: https://raw.githubusercontent.com/caserec/Datasets-for-Recommender-Systems/master/Processed%20Datasets/Anime/anime.zip
ETag: W/"744ea895d173b715e64b9fb5a33ec08b"
Cache-Control: max-age=0, private, must-revalidate
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Frame-Options: deny
X-Content-Type-Options: nosniff
X-XSS-Protection: 0
Referrer-Policy: no-referrer-when-downgrade
Content-Security-Policy: default-src 'none'; base-uri 'self'; child-src github.githubassets.com github.com/assets-cdn/worker/ github.com/assets/ gist.github.com/assets-cdn/worker/; connect-src 'self' uploads.github.com www.githubstatus.com collector.github.com raw.githubusercontent.com api.github.com github-cloud.s3.amazonaws.com github-production-repository-file-5c1aeb.s3.amazonaws.com github-production-upload-manifest-file-7fdce7.s3.amazonaws.com github-production-user-asset-6210df.s3.amazonaws.com *.rel.tunnels.api.visualstudio.com wss://*.rel.tunnels.api.visualstudio.com objects-origin.githubusercontent.com copilot-proxy.githubusercontent.com proxy.individual.githubcopilot.com proxy.business.githubcopilot.com proxy.enterprise.githubcopilot.com *.actions.githubusercontent.com wss://*.actions.githubusercontent.com productionresultssa0.blob.core.windows.net/ productionresultssa1.blob.core.windows.net/ productionresultssa2.blob.core.windows.net/ productionresultssa3.blob.core.windows.net/ productionresultssa4.blob.core.windows.net/ productionresultssa5.blob.core.windows.net/ productionresultssa6.blob.core.windows.net/ productionresultssa7.blob.core.windows.net/ productionresultssa8.blob.core.windows.net/ productionresultssa9.blob.core.windows.net/ productionresultssa10.blob.core.windows.net/ productionresultssa11.blob.core.windows.net/ productionresultssa12.blob.core.windows.net/ productionresultssa13.blob.core.windows.net/ productionresultssa14.blob.core.windows.net/ productionresultssa15.blob.core.windows.net/ productionresultssa16.blob.core.windows.net/ productionresultssa17.blob.core.windows.net/ productionresultssa18.blob.core.windows.net/ productionresultssa19.blob.core.windows.net/ github-production-repository-image-32fea6.s3.amazonaws.com github-production-release-asset-2e65be.s3.amazonaws.com insights.github.com wss://alive.github.com api.githubcopilot.com api.individual.githubcopilot.com api.business.githubcopilot.com api.enterprise.githubcopilot.com; font-src github.githubassets.com; form-action 'self' github.com gist.github.com copilot-workspace.githubnext.com objects-origin.githubusercontent.com; frame-ancestors 'none'; frame-src viewscreen.githubusercontent.com notebooks.githubusercontent.com; img-src 'self' data: blob: github.githubassets.com media.githubusercontent.com camo.githubusercontent.com identicons.github.com avatars.githubusercontent.com private-avatars.githubusercontent.com github-cloud.s3.amazonaws.com objects.githubusercontent.com release-assets.githubusercontent.com secured-user-images.githubusercontent.com/ user-images.githubusercontent.com/ private-user-images.githubusercontent.com opengraph.githubassets.com copilotprodattachments.blob.core.windows.net/github-production-copilot-attachments/ github-production-user-asset-6210df.s3.amazonaws.com customer-stories-feed.github.com spotlights-feed.github.com objects-origin.githubusercontent.com *.githubusercontent.com; manifest-src 'self'; media-src github.com user-images.githubusercontent.com/ secured-user-images.githubusercontent.com/ private-user-images.githubusercontent.com github-production-user-asset-6210df.s3.amazonaws.com gist.github.com; script-src github.githubassets.com; style-src 'unsafe-inline' github.githubassets.com; upgrade-insecure-requests; worker-src github.githubassets.com github.com/assets-cdn/worker/ github.com/assets/ gist.github.com/assets-cdn/worker/
Server: github.com
Accept-Ranges: bytes
Set-Cookie: _gh_sess=6oB7lLQE8Eu8aC2wXjC3IYhG1EtOkD7YZgXA9jfQWGPXT5dZzpLu3ZFGOzH0s3cOevRLVnFNB8P3jaoD%2F7iRmzB5J0thQQyVy8XtXublg0OOeNktOf3epMqYBVAZSPJyn6ZudB1MZ3spjRE3uWpJ6EH3Yeo4K1p%2BABaYH%2F6q6Hza91Z%2FUvhStcilZVnWRg4ngv6ouzeVowESIqBGmxbHX%2BaVz1%2FM3pIDn%2FelM7mehOZOq6wUjxO9yDRS%2BiusQ0D3OnFFRuXF7GL0nhu2AT2JoQ%3D%3D--B%2BQ8UzBumdhaEdiS--YUlBQxHTzMTeWBPpo7jWqg%3D%3D; Path=/; HttpOnly; Secure; SameSite=Lax
Set-Cookie: _octo=GH1.1.1210772471.1749981271; Path=/; Domain=github.com; Expires=Mon, 15 Jun 2026 09:54:31 GMT; Secure; SameSite=Lax
Set-Cookie: logged_in=no; Path=/; Domain=github.com; Expires=Mon, 15 Jun 2026 09:54:31 GMT; HttpOnly; Secure; SameSite=Lax
X-GitHub-Request-Id: 6CAF:2402B3:437542C:45D9F59:684E9857
connection: close
Transfer-Encoding: chunked

]
[2025-06-15 12:56:46,907: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-15 12:56:46,909: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-15 12:56:46,909: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-15 12:56:46,909: INFO: common: created directory at: artifacts]
[2025-06-15 12:56:46,909: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-15 12:56:48,579: INFO: 2366278714: artifacts/data_ingestion/data.zip download! with following info: 
Date: Sun, 15 Jun 2025 09:56:47 GMT
Content-Type: text/html; charset=utf-8
Vary: X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, X-Requested-With,Accept-Encoding, Accept, X-Requested-With
x-repository-download: git clone https://github.com/caserec/Datasets-for-Recommender-Systems.git
x-raw-download: https://raw.githubusercontent.com/caserec/Datasets-for-Recommender-Systems/master/Processed%20Datasets/Steam/steam.zip
ETag: W/"8b05f74fb10e6aa1e365b172fb7d4a3b"
Cache-Control: max-age=0, private, must-revalidate
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Frame-Options: deny
X-Content-Type-Options: nosniff
X-XSS-Protection: 0
Referrer-Policy: no-referrer-when-downgrade
Content-Security-Policy: default-src 'none'; base-uri 'self'; child-src github.githubassets.com github.com/assets-cdn/worker/ github.com/assets/ gist.github.com/assets-cdn/worker/; connect-src 'self' uploads.github.com www.githubstatus.com collector.github.com raw.githubusercontent.com api.github.com github-cloud.s3.amazonaws.com github-production-repository-file-5c1aeb.s3.amazonaws.com github-production-upload-manifest-file-7fdce7.s3.amazonaws.com github-production-user-asset-6210df.s3.amazonaws.com *.rel.tunnels.api.visualstudio.com wss://*.rel.tunnels.api.visualstudio.com objects-origin.githubusercontent.com copilot-proxy.githubusercontent.com proxy.individual.githubcopilot.com proxy.business.githubcopilot.com proxy.enterprise.githubcopilot.com *.actions.githubusercontent.com wss://*.actions.githubusercontent.com productionresultssa0.blob.core.windows.net/ productionresultssa1.blob.core.windows.net/ productionresultssa2.blob.core.windows.net/ productionresultssa3.blob.core.windows.net/ productionresultssa4.blob.core.windows.net/ productionresultssa5.blob.core.windows.net/ productionresultssa6.blob.core.windows.net/ productionresultssa7.blob.core.windows.net/ productionresultssa8.blob.core.windows.net/ productionresultssa9.blob.core.windows.net/ productionresultssa10.blob.core.windows.net/ productionresultssa11.blob.core.windows.net/ productionresultssa12.blob.core.windows.net/ productionresultssa13.blob.core.windows.net/ productionresultssa14.blob.core.windows.net/ productionresultssa15.blob.core.windows.net/ productionresultssa16.blob.core.windows.net/ productionresultssa17.blob.core.windows.net/ productionresultssa18.blob.core.windows.net/ productionresultssa19.blob.core.windows.net/ github-production-repository-image-32fea6.s3.amazonaws.com github-production-release-asset-2e65be.s3.amazonaws.com insights.github.com wss://alive.github.com api.githubcopilot.com api.individual.githubcopilot.com api.business.githubcopilot.com api.enterprise.githubcopilot.com; font-src github.githubassets.com; form-action 'self' github.com gist.github.com copilot-workspace.githubnext.com objects-origin.githubusercontent.com; frame-ancestors 'none'; frame-src viewscreen.githubusercontent.com notebooks.githubusercontent.com; img-src 'self' data: blob: github.githubassets.com media.githubusercontent.com camo.githubusercontent.com identicons.github.com avatars.githubusercontent.com private-avatars.githubusercontent.com github-cloud.s3.amazonaws.com objects.githubusercontent.com release-assets.githubusercontent.com secured-user-images.githubusercontent.com/ user-images.githubusercontent.com/ private-user-images.githubusercontent.com opengraph.githubassets.com copilotprodattachments.blob.core.windows.net/github-production-copilot-attachments/ github-production-user-asset-6210df.s3.amazonaws.com customer-stories-feed.github.com spotlights-feed.github.com objects-origin.githubusercontent.com *.githubusercontent.com; manifest-src 'self'; media-src github.com user-images.githubusercontent.com/ secured-user-images.githubusercontent.com/ private-user-images.githubusercontent.com github-production-user-asset-6210df.s3.amazonaws.com gist.github.com; script-src github.githubassets.com; style-src 'unsafe-inline' github.githubassets.com; upgrade-insecure-requests; worker-src github.githubassets.com github.com/assets-cdn/worker/ github.com/assets/ gist.github.com/assets-cdn/worker/
Server: github.com
Accept-Ranges: bytes
Set-Cookie: _gh_sess=Cq%2BoH7ZxDsG0xCLFQ1QDUtgDHDLiVifUr44ETBSvkXOtbw9puykD6j7cnsjNsBa2jWg6RzAKnLJIFU3DcbiyA0SUcw3LhxcS%2FmkRF02bdlS9haSlQTIdHry5K2G1DIsbdlKYJDeYCSCKcigNK7qugTUzI3LZ%2B68e2hJze0qcxZXk1437fsIonc9mUPeV2lLPhO%2BtG3vMw1UObmReV%2B15IEsDdVXDAB%2Fs%2FUsFm3EWc7Rc5lM3ZHDHi9VViYHltEPOuRU80%2FjhaXq2ypOh3zUySg%3D%3D--WP0ILDMpKRZ2H3Lf--A1IMQYpgEQqbOcm3Zi71sA%3D%3D; Path=/; HttpOnly; Secure; SameSite=Lax
Set-Cookie: _octo=GH1.1.1911766261.1749981407; Path=/; Domain=github.com; Expires=Mon, 15 Jun 2026 09:56:47 GMT; Secure; SameSite=Lax
Set-Cookie: logged_in=no; Path=/; Domain=github.com; Expires=Mon, 15 Jun 2026 09:56:47 GMT; HttpOnly; Secure; SameSite=Lax
X-GitHub-Request-Id: 93EB:24A895:3D68FE5:3F8CE17:684E98DE
connection: close
Transfer-Encoding: chunked

]
[2025-06-15 12:57:44,213: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-15 12:57:44,216: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-15 12:57:44,219: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-15 12:57:44,221: INFO: common: created directory at: artifacts]
[2025-06-15 12:57:44,222: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-15 12:57:44,223: INFO: 2366278714: File already exists of size: ~ 177 KB]
[2025-06-15 12:59:13,395: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-15 12:59:13,398: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-15 12:59:13,401: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-15 12:59:13,403: INFO: common: created directory at: artifacts]
[2025-06-15 12:59:13,404: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-15 12:59:13,406: INFO: 2366278714: File already exists of size: ~ 177 KB]
[2025-06-15 12:59:59,964: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-15 12:59:59,967: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-15 12:59:59,967: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-15 12:59:59,972: INFO: common: created directory at: artifacts]
[2025-06-15 12:59:59,972: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-15 12:59:59,972: INFO: 2366278714: File already exists of size: ~ 177 KB]
[2025-06-15 13:00:16,051: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-15 13:00:16,051: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-15 13:00:16,051: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-15 13:00:16,051: INFO: common: created directory at: artifacts]
[2025-06-15 13:00:16,051: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-15 13:00:16,051: INFO: 2366278714: File already exists of size: ~ 177 KB]
[2025-06-15 13:01:23,808: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-15 13:01:23,811: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-15 13:01:23,811: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-15 13:01:23,811: INFO: common: created directory at: artifacts]
[2025-06-15 13:01:23,816: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-15 13:01:23,816: INFO: 2366278714: File already exists of size: ~ 177 KB]
[2025-06-15 13:01:45,648: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-15 13:01:45,648: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-15 13:01:45,660: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-15 13:01:45,660: INFO: common: created directory at: artifacts]
[2025-06-15 13:01:45,660: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-15 13:02:32,205: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-15 13:02:32,209: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-15 13:02:32,213: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-15 13:02:32,214: INFO: common: created directory at: artifacts]
[2025-06-15 13:02:32,214: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-15 13:03:11,667: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-15 13:03:11,675: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-15 13:03:11,675: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-15 13:03:11,675: INFO: common: created directory at: artifacts]
[2025-06-15 13:03:11,681: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-15 13:11:05,348: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-15 13:11:05,348: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-15 13:11:05,348: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-15 13:11:05,348: INFO: common: created directory at: artifacts]
[2025-06-15 13:11:05,348: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-15 13:11:06,854: INFO: 2366278714: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 23329
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "c69888a4ae59bc5a893392785a938ccd4937981c06ba8a9d6a21aa52b4ab5b6e"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: D7B1:13A383:FA23ED:11D2311:684E9828
Accept-Ranges: bytes
Date: Sun, 15 Jun 2025 10:11:06 GMT
Via: 1.1 varnish
X-Served-By: cache-mrs10555-MRS
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1749982266.953092,VS0,VE178
Vary: Authorization,Accept-Encoding
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: d5a6fcc77be8f2275d1abc1423a73405516c6d69
Expires: Sun, 15 Jun 2025 10:16:06 GMT
Source-Age: 0

]
[2025-06-15 13:13:08,754: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-15 13:13:08,761: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-15 13:13:08,764: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-15 13:13:08,766: INFO: common: created directory at: artifacts]
[2025-06-15 13:13:08,767: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-15 13:13:10,039: INFO: 2366278714: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 23329
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "c69888a4ae59bc5a893392785a938ccd4937981c06ba8a9d6a21aa52b4ab5b6e"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 1CCF:33F5ED:30C14E6:368D96A:684E9CB5
Accept-Ranges: bytes
Date: Sun, 15 Jun 2025 10:13:09 GMT
Via: 1.1 varnish
X-Served-By: cache-mxp6928-MXP
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1749982389.128799,VS0,VE161
Vary: Authorization,Accept-Encoding
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: c55c8b05534b7b77d0d7dc417048ea90581fc1d4
Expires: Sun, 15 Jun 2025 10:18:09 GMT
Source-Age: 0

]
[2025-06-15 13:14:23,983: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-15 13:14:23,983: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-15 13:14:23,993: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-15 13:14:23,993: INFO: common: created directory at: artifacts]
[2025-06-15 13:14:23,993: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-15 13:14:26,332: INFO: 2366278714: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 823340
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "b50f2b016b71c8f56fcb554cbf4163293e7882218ccc88b128d052089d919455"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 9746:208251:5A5A5:65DCB:684E9CFF
Accept-Ranges: bytes
Date: Sun, 15 Jun 2025 10:14:24 GMT
Via: 1.1 varnish
X-Served-By: cache-mrs1050088-MRS
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1749982465.547583,VS0,VE193
Vary: Authorization,Accept-Encoding
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 8301062d68595bfd508ef824ac1d5b7f73534b0b
Expires: Sun, 15 Jun 2025 10:19:24 GMT
Source-Age: 0

]
[2025-06-15 13:31:06,889: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-15 13:31:06,900: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-15 13:31:06,911: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-15 13:31:06,915: INFO: common: created directory at: artifacts]
[2025-06-15 13:31:06,915: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-15 13:31:09,888: INFO: 2366278714: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 1908730
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "88554daa7a6edc5832f3dbe2884e7a2c24af24e5d614d1fe5dfc82ce9904f363"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: BC91:110342:2FD3E7C:35A136A:684EA0EA
Accept-Ranges: bytes
Date: Sun, 15 Jun 2025 10:31:07 GMT
Via: 1.1 varnish
X-Served-By: cache-mrs10527-MRS
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1749983468.631523,VS0,VE128
Vary: Authorization,Accept-Encoding
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: bc0681213de52ac482570a04f3ea4b228ce02b55
Expires: Sun, 15 Jun 2025 10:36:07 GMT
Source-Age: 0

]
[2025-06-15 13:37:04,833: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-15 13:37:04,837: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-15 13:37:04,838: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-15 13:37:04,840: INFO: common: created directory at: artifacts]
[2025-06-15 13:38:14,428: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-15 13:38:14,435: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-15 13:38:14,436: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-15 13:38:14,440: INFO: common: created directory at: artifacts]
[2025-06-15 13:38:44,531: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-15 13:38:44,534: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-15 13:38:44,535: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-15 13:38:44,535: INFO: common: created directory at: artifacts]
[2025-06-15 13:49:14,341: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-15 13:49:14,341: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-15 13:49:14,346: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-15 13:49:14,346: INFO: common: created directory at: artifacts]
[2025-06-15 13:49:14,349: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-15 13:49:14,349: INFO: 2366278714: File already exists of size: ~ 1864 KB]
[2025-06-15 13:49:40,270: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-15 13:49:40,272: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-15 13:49:40,272: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-15 13:49:40,272: INFO: common: created directory at: artifacts]
[2025-06-15 13:49:40,272: INFO: common: created directory at: artifacts/data_validation]
[2025-06-15 13:50:27,251: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-15 13:50:27,261: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-15 13:50:27,261: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-15 13:50:27,261: INFO: common: created directory at: artifacts]
[2025-06-15 13:50:27,261: INFO: common: created directory at: artifacts/data_validation]
[2025-06-15 14:07:59,455: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-15 14:07:59,455: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-15 14:07:59,455: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-15 14:07:59,455: INFO: common: created directory at: artifacts]
[2025-06-15 14:07:59,455: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-15 14:08:00,773: INFO: 2366278714: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 23329
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "c69888a4ae59bc5a893392785a938ccd4937981c06ba8a9d6a21aa52b4ab5b6e"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: D7B1:13A383:FA23ED:11D2311:684E9828
Accept-Ranges: bytes
Date: Sun, 15 Jun 2025 11:08:00 GMT
Via: 1.1 varnish
X-Served-By: cache-mrs10533-MRS
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1749985680.077241,VS0,VE166
Vary: Authorization,Accept-Encoding
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: eb5b5ca77f2523cbe82b354b678d66c5e6914252
Expires: Sun, 15 Jun 2025 11:13:00 GMT
Source-Age: 0

]
[2025-06-15 14:09:12,388: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-15 14:09:12,392: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-15 14:09:12,392: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-15 14:09:12,392: INFO: common: created directory at: artifacts]
[2025-06-15 14:09:12,397: INFO: common: created directory at: artifacts/data_validation]
[2025-06-15 14:18:45,774: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-15 14:18:45,776: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-15 14:18:45,779: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-15 14:18:45,780: INFO: common: created directory at: artifacts]
[2025-06-15 14:19:18,845: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-15 14:19:18,845: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-15 14:19:18,848: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-15 14:19:18,852: INFO: common: created directory at: artifacts]
[2025-06-15 14:19:18,853: INFO: common: created directory at: artifacts/data_transformation]
[2025-06-15 14:19:18,902: INFO: 2148425976: Splited data into training and test sets]
[2025-06-15 14:19:18,902: INFO: 2148425976: (1199, 12)]
[2025-06-15 14:19:18,907: INFO: 2148425976: (400, 12)]
[2025-06-15 14:23:48,100: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-15 14:23:48,100: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-15 14:23:48,105: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-15 14:23:48,107: INFO: common: created directory at: artifacts]
[2025-06-15 14:23:48,107: INFO: common: created directory at: artifacts/model_trainer]
[2025-06-15 14:25:57,283: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-15 14:25:57,288: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-15 14:25:57,288: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-15 14:25:57,288: INFO: common: created directory at: artifacts]
[2025-06-15 14:26:32,962: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-15 14:26:32,962: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-15 14:26:32,970: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-15 14:26:32,973: INFO: common: created directory at: artifacts]
[2025-06-15 14:26:32,974: INFO: common: created directory at: artifacts/model_evaluation]
[2025-06-15 14:27:42,815: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-15 14:27:42,819: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-15 14:27:42,820: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-15 14:27:42,820: INFO: common: created directory at: artifacts]
[2025-06-15 14:27:42,826: INFO: common: created directory at: artifacts/model_evaluation]
[2025-06-15 14:27:42,961: INFO: common: json file saved at: artifacts\model_evaluation\metrics.json]
[2025-06-15 17:50:03,839: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-15 17:50:03,839: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-15 17:50:03,853: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-15 17:50:03,854: INFO: common: created directory at: artifacts]
[2025-06-15 17:50:03,855: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-15 17:50:05,227: INFO: 2366278714: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 23329
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "c69888a4ae59bc5a893392785a938ccd4937981c06ba8a9d6a21aa52b4ab5b6e"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 5391:FB27C:346F688:3AA71CA:684EDD9C
Accept-Ranges: bytes
Date: Sun, 15 Jun 2025 14:50:05 GMT
Via: 1.1 varnish
X-Served-By: cache-mrs1050084-MRS
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1749999005.980329,VS0,VE178
Vary: Authorization,Accept-Encoding
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 0b5808814020d01095c5dfc94f0307a1f8265351
Expires: Sun, 15 Jun 2025 14:55:05 GMT
Source-Age: 0

]
[2025-06-15 17:50:22,034: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-15 17:50:22,034: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-15 17:50:22,034: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-15 17:50:22,034: INFO: common: created directory at: artifacts]
[2025-06-15 17:50:22,034: INFO: common: created directory at: artifacts/data_validation]
[2025-06-15 17:50:54,668: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-15 17:50:54,670: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-15 17:50:54,672: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-15 17:50:54,674: INFO: common: created directory at: artifacts]
[2025-06-15 17:50:55,330: INFO: common: created directory at: artifacts/data_transformation]
[2025-06-15 17:50:55,363: INFO: 2148425976: Splited data into training and test sets]
[2025-06-15 17:50:55,363: INFO: 2148425976: (1199, 12)]
[2025-06-15 17:50:55,363: INFO: 2148425976: (400, 12)]
[2025-06-15 17:51:09,079: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-15 17:51:09,079: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-15 17:51:09,079: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-15 17:51:09,079: INFO: common: created directory at: artifacts]
[2025-06-15 17:51:09,079: INFO: common: created directory at: artifacts/model_trainer]
[2025-06-15 17:51:50,397: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-15 17:51:50,397: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-15 17:51:50,397: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-15 17:51:50,397: INFO: common: created directory at: artifacts]
[2025-06-15 17:51:50,397: INFO: common: created directory at: artifacts/model_evaluation]
[2025-06-15 17:51:50,471: INFO: common: json file saved at: artifacts\model_evaluation\metrics.json]
[2025-06-16 08:42:44,230: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-16 08:42:44,263: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-16 08:42:44,279: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-16 08:42:44,284: INFO: common: created directory at: artifacts]
[2025-06-16 08:42:44,284: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-16 08:42:44,284: INFO: 2366278714: File already exists of size: ~ 23 KB]
[2025-06-16 08:51:35,535: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-16 08:51:35,538: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-16 08:51:35,538: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-16 08:51:35,538: INFO: common: created directory at: artifacts]
[2025-06-16 08:51:35,538: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-16 08:51:39,625: INFO: 2366278714: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 2156533
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "6aa8628c5716b40e453b430d9afcdc990790e8d187fa79f226a6b265b946061c"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: A6D8:32227B:3B9B328:41652D0:684FB0E8
Accept-Ranges: bytes
Date: Mon, 16 Jun 2025 05:51:37 GMT
Via: 1.1 varnish
X-Served-By: cache-mrs10556-MRS
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1750053097.297889,VS0,VE241
Vary: Authorization,Accept-Encoding
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 16a2a6237b1aefa97f090946163e8e7e7c40435c
Expires: Mon, 16 Jun 2025 05:56:37 GMT
Source-Age: 0

]
[2025-06-16 08:56:29,255: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-16 08:56:29,255: INFO: common: created directory at: artifacts]
[2025-06-16 08:56:29,259: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-16 08:56:34,114: INFO: 2366278714: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 2156533
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "6aa8628c5716b40e453b430d9afcdc990790e8d187fa79f226a6b265b946061c"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: A6D8:32227B:3B9B328:41652D0:684FB0E8
Accept-Ranges: bytes
Date: Mon, 16 Jun 2025 05:56:30 GMT
Via: 1.1 varnish
X-Served-By: cache-mrs10555-MRS
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1750053391.915485,VS0,VE1
Vary: Authorization,Accept-Encoding
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 4d96d5d9afbce08bc6bbfb8ee8f63e355cfeff9f
Expires: Mon, 16 Jun 2025 06:01:30 GMT
Source-Age: 293

]
[2025-06-16 08:57:34,806: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-16 08:57:34,806: INFO: common: created directory at: artifacts]
[2025-06-16 08:57:34,810: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-16 08:57:34,810: INFO: 358775567: File already exists of size: ~ 2106 KB]
[2025-06-16 09:59:27,603: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-16 09:59:27,686: INFO: common: created directory at: artifacts]
[2025-06-16 09:59:27,697: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-16 10:00:05,383: INFO: 358775567: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 2156533
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "6aa8628c5716b40e453b430d9afcdc990790e8d187fa79f226a6b265b946061c"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: A6D8:32227B:3B9B328:41652D0:684FB0E8
Accept-Ranges: bytes
Date: Mon, 16 Jun 2025 06:59:30 GMT
Via: 1.1 varnish
X-Served-By: cache-mrs1050100-MRS
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1750057170.978505,VS0,VE194
Vary: Authorization,Accept-Encoding
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: be4e988bb34c34b07d713978f2334dbfc91cc12e
Expires: Mon, 16 Jun 2025 07:04:30 GMT
Source-Age: 0

]
[2025-06-16 10:01:41,793: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-16 10:01:41,793: INFO: common: created directory at: artifacts]
[2025-06-16 10:01:41,793: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-16 10:01:41,802: INFO: 1371079687: Downloading dataset from Kaggle: https://github.com/caserec/Datasets-for-Recommender-Systems/raw/refs/heads/master/Processed%20Datasets/BookCrossing/book_crossing.zip]
[2025-06-16 10:02:46,394: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-16 10:02:46,394: INFO: common: created directory at: artifacts]
[2025-06-16 10:02:46,402: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-16 10:02:46,402: INFO: 1371079687: Downloading dataset from Kaggle: rounakbanik/movies]
[2025-06-16 10:06:52,069: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-16 10:06:52,070: INFO: common: created directory at: artifacts]
[2025-06-16 10:06:52,072: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-16 10:06:52,074: INFO: 1371079687: Downloading dataset from Kaggle: parasharmanas/movie-recommendation-system]
[2025-06-16 10:11:41,742: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-16 10:11:41,742: INFO: common: created directory at: artifacts]
[2025-06-16 10:11:41,742: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-16 10:11:41,742: INFO: 1371079687: Downloading dataset from Kaggle: arashnic/book-recommendation-dataset]
[2025-06-16 10:12:10,703: INFO: 1371079687: Downloaded dataset to: artifacts/data_ingestion/data.zip]
[2025-06-16 10:28:12,633: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-16 10:28:12,635: INFO: common: created directory at: artifacts]
[2025-06-16 10:28:12,636: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-16 10:28:12,638: INFO: 2545639116: Downloading dataset from Kaggle: arashnic/book-recommendation-dataset]
[2025-06-16 10:28:31,841: INFO: 2545639116: Downloaded dataset to: artifacts/data_ingestion/data.zip]
[2025-06-16 10:31:47,212: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-16 10:31:47,214: INFO: common: created directory at: artifacts]
[2025-06-16 10:31:47,215: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-16 10:31:47,217: INFO: 1848273549: File already exists of size: ~ 0 KB]
[2025-06-16 10:32:03,142: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-16 10:32:03,143: INFO: common: created directory at: artifacts]
[2025-06-16 10:32:03,144: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-16 10:32:03,145: INFO: 1848273549: Downloading dataset from Kaggle: arashnic/book-recommendation-dataset]
[2025-06-16 10:32:28,390: INFO: 1848273549: Downloaded dataset to: artifacts/data_ingestion/data.zip]
[2025-06-16 10:34:02,300: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-16 10:34:02,302: INFO: common: created directory at: artifacts]
[2025-06-16 10:34:02,303: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-16 10:34:02,304: INFO: 1284476475: Downloading dataset from Kaggle: arashnic/book-recommendation-dataset]
[2025-06-16 10:34:25,802: INFO: 1284476475: Downloaded dataset to: artifacts/data_ingestion/data.zip]
[2025-06-16 10:34:26,160: INFO: 1284476475: Extracted data to: artifacts/data_ingestion]
[2025-06-16 10:35:20,810: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-16 10:35:20,811: INFO: common: created directory at: artifacts]
[2025-06-16 10:35:20,812: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-16 10:35:20,813: INFO: 1284476475: Downloading dataset from Kaggle: arashnic/book-recommendation-dataset]
[2025-06-16 10:35:49,574: INFO: 1284476475: Downloaded dataset to: artifacts/data_ingestion/data.zip]
[2025-06-16 10:35:49,993: INFO: 1284476475: Extracted data to: artifacts/data_ingestion/data]
[2025-06-16 14:21:52,479: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-16 14:21:52,487: INFO: common: created directory at: artifacts]
[2025-06-16 14:21:52,487: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-16 14:21:52,491: INFO: 1284476475: Downloading dataset from Kaggle: arashnic/book-recommendation-dataset]
[2025-06-16 14:22:16,538: INFO: 1284476475: Downloaded dataset to: artifacts/data_ingestion/data.zip]
[2025-06-16 14:22:17,101: INFO: 1284476475: Extracted data to: artifacts/data_ingestion/data]
[2025-06-16 14:23:06,007: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-16 14:23:06,009: INFO: common: created directory at: artifacts]
[2025-06-16 14:23:06,010: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-16 14:23:06,010: INFO: 1266010482: File already exists of size: ~ 24903 KB]
[2025-06-16 14:23:06,795: INFO: 1266010482: Extracted data to: artifacts/data_ingestion/data]
[2025-06-16 14:23:06,795: INFO: 1266010482: Reading data files from artifacts/data_ingestion/data]
[2025-06-16 14:23:09,811: INFO: 1266010482: Books shape: (271360, 8), Ratings shape: (1149780, 3), Users shape: (278858, 3)]
[2025-06-16 14:23:09,811: INFO: 1266010482: Merging ratings with books...]
[2025-06-16 14:23:12,801: INFO: 1266010482: Merging with users...]
[2025-06-16 14:23:13,677: INFO: 1266010482: Merged dataset shape: (1149780, 12)]
[2025-06-16 14:23:24,759: INFO: 1266010482: Saved merged data to artifacts/data_ingestion\merged_data.csv]
[2025-06-16 14:42:05,564: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-16 14:42:05,591: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-16 14:42:05,599: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-16 14:42:05,608: INFO: common: created directory at: artifacts]
[2025-06-16 14:42:05,614: INFO: common: created directory at: artifacts/data_validation]
[2025-06-16 15:06:56,853: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-16 15:06:56,853: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-16 15:06:56,853: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-16 15:06:56,863: INFO: common: created directory at: artifacts]
[2025-06-16 15:06:56,864: INFO: common: created directory at: artifacts/data_validation]
[2025-06-16 15:24:24,231: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-16 15:24:24,239: INFO: common: created directory at: artifacts]
[2025-06-16 15:24:24,239: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-16 15:24:24,243: INFO: 1266010482: Downloading dataset from Kaggle: arashnic/book-recommendation-dataset]
[2025-06-16 15:26:28,724: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-16 15:26:28,724: INFO: common: created directory at: artifacts]
[2025-06-16 15:26:28,724: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-16 15:26:28,724: INFO: 1266010482: Downloading dataset from Kaggle: arashnic/book-recommendation-dataset]
[2025-06-16 15:27:02,440: INFO: 1266010482: Downloaded dataset to: artifacts/data_ingestion/data.zip]
[2025-06-16 15:27:02,839: INFO: 1266010482: Extracted data to: artifacts/data_ingestion/data]
[2025-06-16 15:27:02,839: INFO: 1266010482: Reading data files from artifacts/data_ingestion/data]
[2025-06-16 15:27:04,918: INFO: 1266010482: Books shape: (271360, 8), Ratings shape: (1149780, 3), Users shape: (278858, 3)]
[2025-06-16 15:27:04,918: INFO: 1266010482: Merging ratings with books...]
[2025-06-16 15:27:05,552: INFO: 1266010482: Merging with users...]
[2025-06-16 15:27:05,992: INFO: 1266010482: Merged dataset shape: (1149780, 12)]
[2025-06-16 15:27:14,077: INFO: 1266010482: Saved merged data to artifacts/data_ingestion\merged_data.csv]
[2025-06-16 15:30:52,698: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-16 15:30:52,698: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-16 15:30:52,706: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-16 15:30:52,706: INFO: common: created directory at: artifacts]
[2025-06-16 15:30:52,706: INFO: common: created directory at: artifacts/data_validation]
[2025-06-16 15:38:44,662: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-16 15:38:44,675: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-16 15:38:44,684: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-16 15:38:44,689: INFO: common: created directory at: artifacts]
[2025-06-16 15:38:44,690: INFO: common: created directory at: artifacts/data_validation]
[2025-06-16 15:41:06,876: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-16 15:41:06,876: INFO: common: created directory at: artifacts]
[2025-06-16 15:41:06,876: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-16 15:41:06,876: INFO: 2369448649: Downloading dataset from Kaggle: arashnic/book-recommendation-dataset]
[2025-06-16 15:41:59,017: INFO: 2369448649: Downloaded dataset to: artifacts/data_ingestion/data.zip]
[2025-06-16 15:41:59,401: INFO: 2369448649: Extracted data to: artifacts/data_ingestion/data]
[2025-06-16 15:41:59,401: INFO: 2369448649: Reading data files with specified dtypes...]
[2025-06-16 15:42:00,605: ERROR: 2369448649: Error in merge_data: Unable to parse string "DK Publishing Inc" at position 12930]
Traceback (most recent call last):
  File "pandas/_libs/lib.pyx", line 2407, in pandas._libs.lib.maybe_convert_numeric
ValueError: Unable to parse string "DK Publishing Inc"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\newst\AppData\Local\Temp\ipykernel_20696\2369448649.py", line 76, in merge_data
    books_df = pd.read_csv(
               ^^^^^^^^^^^^
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\io\parsers\readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\io\parsers\readers.py", line 626, in _read
    return parser.read(nrows)
           ^^^^^^^^^^^^^^^^^^
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\io\parsers\readers.py", line 1923, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\io\parsers\c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pandas/_libs/parsers.pyx", line 838, in pandas._libs.parsers.TextReader.read_low_memory
  File "pandas/_libs/parsers.pyx", line 921, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 1066, in pandas._libs.parsers.TextReader._convert_column_data
  File "pandas/_libs/parsers.pyx", line 1105, in pandas._libs.parsers.TextReader._convert_tokens
  File "pandas/_libs/parsers.pyx", line 1211, in pandas._libs.parsers.TextReader._convert_with_dtype
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\core\arrays\numeric.py", line 283, in _from_sequence_of_strings
    scalars = to_numeric(strings, errors="raise", dtype_backend="numpy_nullable")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\core\tools\numeric.py", line 235, in to_numeric
    values, new_mask = lib.maybe_convert_numeric(  # type: ignore[call-overload]
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pandas/_libs/lib.pyx", line 2449, in pandas._libs.lib.maybe_convert_numeric
ValueError: Unable to parse string "DK Publishing Inc" at position 12930
[2025-06-16 15:48:29,054: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-16 15:48:29,054: INFO: common: created directory at: artifacts]
[2025-06-16 15:48:29,054: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-16 15:48:29,065: INFO: 86415195: Downloading dataset from Kaggle: arashnic/book-recommendation-dataset]
[2025-06-16 15:49:31,291: INFO: 86415195: Downloaded dataset to: artifacts/data_ingestion/data.zip]
[2025-06-16 15:49:31,641: INFO: 86415195: Extracted data to: artifacts/data_ingestion/data]
[2025-06-16 15:49:31,641: INFO: 86415195: Reading data files with specified dtypes...]
[2025-06-16 15:49:32,991: ERROR: 86415195: Error in merge_data: Unable to parse string "DK Publishing Inc" at position 12930]
Traceback (most recent call last):
  File "pandas/_libs/lib.pyx", line 2407, in pandas._libs.lib.maybe_convert_numeric
ValueError: Unable to parse string "DK Publishing Inc"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\newst\AppData\Local\Temp\ipykernel_21448\86415195.py", line 76, in merge_data
    books_df = pd.read_csv(
               ^^^^^^^^^^^^
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\io\parsers\readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\io\parsers\readers.py", line 626, in _read
    return parser.read(nrows)
           ^^^^^^^^^^^^^^^^^^
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\io\parsers\readers.py", line 1923, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\io\parsers\c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pandas/_libs/parsers.pyx", line 838, in pandas._libs.parsers.TextReader.read_low_memory
  File "pandas/_libs/parsers.pyx", line 921, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 1066, in pandas._libs.parsers.TextReader._convert_column_data
  File "pandas/_libs/parsers.pyx", line 1105, in pandas._libs.parsers.TextReader._convert_tokens
  File "pandas/_libs/parsers.pyx", line 1211, in pandas._libs.parsers.TextReader._convert_with_dtype
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\core\arrays\numeric.py", line 283, in _from_sequence_of_strings
    scalars = to_numeric(strings, errors="raise", dtype_backend="numpy_nullable")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\core\tools\numeric.py", line 235, in to_numeric
    values, new_mask = lib.maybe_convert_numeric(  # type: ignore[call-overload]
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pandas/_libs/lib.pyx", line 2449, in pandas._libs.lib.maybe_convert_numeric
ValueError: Unable to parse string "DK Publishing Inc" at position 12930
[2025-06-16 15:54:13,128: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-16 15:54:13,128: INFO: common: created directory at: artifacts]
[2025-06-16 15:54:13,128: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-16 15:54:13,128: INFO: 2410516760: Downloading dataset from Kaggle: arashnic/book-recommendation-dataset]
[2025-06-16 15:54:45,053: INFO: 2410516760: Downloaded dataset to: artifacts/data_ingestion/data.zip]
[2025-06-16 15:54:45,416: INFO: 2410516760: Extracted data to: artifacts/data_ingestion/data]
[2025-06-16 15:54:45,416: INFO: 2410516760: Reading data files with specified dtypes...]
[2025-06-16 15:54:46,451: ERROR: 2410516760: Error in merge_data: Unable to parse string "DK Publishing Inc" at position 12930]
Traceback (most recent call last):
  File "pandas/_libs/lib.pyx", line 2407, in pandas._libs.lib.maybe_convert_numeric
ValueError: Unable to parse string "DK Publishing Inc"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\newst\AppData\Local\Temp\ipykernel_19640\2410516760.py", line 75, in merge_data
    books_df = pd.read_csv(
               ^^^^^^^^^^^^
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\io\parsers\readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\io\parsers\readers.py", line 626, in _read
    return parser.read(nrows)
           ^^^^^^^^^^^^^^^^^^
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\io\parsers\readers.py", line 1923, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\io\parsers\c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pandas/_libs/parsers.pyx", line 838, in pandas._libs.parsers.TextReader.read_low_memory
  File "pandas/_libs/parsers.pyx", line 921, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 1066, in pandas._libs.parsers.TextReader._convert_column_data
  File "pandas/_libs/parsers.pyx", line 1105, in pandas._libs.parsers.TextReader._convert_tokens
  File "pandas/_libs/parsers.pyx", line 1211, in pandas._libs.parsers.TextReader._convert_with_dtype
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\core\arrays\numeric.py", line 283, in _from_sequence_of_strings
    scalars = to_numeric(strings, errors="raise", dtype_backend="numpy_nullable")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\core\tools\numeric.py", line 235, in to_numeric
    values, new_mask = lib.maybe_convert_numeric(  # type: ignore[call-overload]
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pandas/_libs/lib.pyx", line 2449, in pandas._libs.lib.maybe_convert_numeric
ValueError: Unable to parse string "DK Publishing Inc" at position 12930
[2025-06-16 15:57:37,263: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-16 15:57:37,264: INFO: common: created directory at: artifacts]
[2025-06-16 15:57:37,266: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-16 15:57:37,266: INFO: 2410516760: Downloading dataset from Kaggle: arashnic/book-recommendation-dataset]
[2025-06-16 15:57:57,225: INFO: 2410516760: Downloaded dataset to: artifacts/data_ingestion/data.zip]
[2025-06-16 15:57:57,711: INFO: 2410516760: Extracted data to: artifacts/data_ingestion/data]
[2025-06-16 15:57:57,720: INFO: 2410516760: Reading data files with specified dtypes...]
[2025-06-16 15:57:58,824: ERROR: 2410516760: Error in merge_data: Unable to parse string "DK Publishing Inc" at position 12930]
Traceback (most recent call last):
  File "pandas/_libs/lib.pyx", line 2407, in pandas._libs.lib.maybe_convert_numeric
ValueError: Unable to parse string "DK Publishing Inc"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\newst\AppData\Local\Temp\ipykernel_22768\2410516760.py", line 75, in merge_data
    books_df = pd.read_csv(
               ^^^^^^^^^^^^
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\io\parsers\readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\io\parsers\readers.py", line 626, in _read
    return parser.read(nrows)
           ^^^^^^^^^^^^^^^^^^
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\io\parsers\readers.py", line 1923, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\io\parsers\c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pandas/_libs/parsers.pyx", line 838, in pandas._libs.parsers.TextReader.read_low_memory
  File "pandas/_libs/parsers.pyx", line 921, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 1066, in pandas._libs.parsers.TextReader._convert_column_data
  File "pandas/_libs/parsers.pyx", line 1105, in pandas._libs.parsers.TextReader._convert_tokens
  File "pandas/_libs/parsers.pyx", line 1211, in pandas._libs.parsers.TextReader._convert_with_dtype
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\core\arrays\numeric.py", line 283, in _from_sequence_of_strings
    scalars = to_numeric(strings, errors="raise", dtype_backend="numpy_nullable")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\core\tools\numeric.py", line 235, in to_numeric
    values, new_mask = lib.maybe_convert_numeric(  # type: ignore[call-overload]
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pandas/_libs/lib.pyx", line 2449, in pandas._libs.lib.maybe_convert_numeric
ValueError: Unable to parse string "DK Publishing Inc" at position 12930
[2025-06-16 16:03:02,542: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-16 16:03:02,542: INFO: common: created directory at: artifacts]
[2025-06-16 16:03:02,542: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-16 16:03:02,542: INFO: 1319989155: Downloading dataset from Kaggle: arashnic/book-recommendation-dataset]
[2025-06-16 16:03:26,483: INFO: 1319989155: Downloaded dataset to: artifacts/data_ingestion/data.zip]
[2025-06-16 16:03:26,829: INFO: 1319989155: Extracted data to: artifacts/data_ingestion/data]
[2025-06-16 16:03:26,829: INFO: 1319989155: Reading data files with specified dtypes...]
[2025-06-16 16:03:27,849: ERROR: 1319989155: Error in merge_data: Unable to parse string "DK Publishing Inc" at position 12930]
Traceback (most recent call last):
  File "pandas/_libs/lib.pyx", line 2407, in pandas._libs.lib.maybe_convert_numeric
ValueError: Unable to parse string "DK Publishing Inc"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\newst\AppData\Local\Temp\ipykernel_15448\1319989155.py", line 82, in merge_data
    books_df = pd.read_csv(
               ^^^^^^^^^^^^
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\io\parsers\readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\io\parsers\readers.py", line 626, in _read
    return parser.read(nrows)
           ^^^^^^^^^^^^^^^^^^
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\io\parsers\readers.py", line 1923, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\io\parsers\c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pandas/_libs/parsers.pyx", line 838, in pandas._libs.parsers.TextReader.read_low_memory
  File "pandas/_libs/parsers.pyx", line 921, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 1066, in pandas._libs.parsers.TextReader._convert_column_data
  File "pandas/_libs/parsers.pyx", line 1105, in pandas._libs.parsers.TextReader._convert_tokens
  File "pandas/_libs/parsers.pyx", line 1211, in pandas._libs.parsers.TextReader._convert_with_dtype
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\core\arrays\numeric.py", line 283, in _from_sequence_of_strings
    scalars = to_numeric(strings, errors="raise", dtype_backend="numpy_nullable")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\core\tools\numeric.py", line 235, in to_numeric
    values, new_mask = lib.maybe_convert_numeric(  # type: ignore[call-overload]
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pandas/_libs/lib.pyx", line 2449, in pandas._libs.lib.maybe_convert_numeric
ValueError: Unable to parse string "DK Publishing Inc" at position 12930
[2025-06-16 16:14:25,467: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-16 16:14:25,467: INFO: common: created directory at: artifacts]
[2025-06-16 16:14:25,467: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-16 16:14:25,467: INFO: 1823720442: Downloading dataset from Kaggle: arashnic/book-recommendation-dataset]
[2025-06-17 04:57:01,393: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-17 04:57:01,419: INFO: common: created directory at: artifacts]
[2025-06-17 04:57:01,419: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-17 04:57:01,424: INFO: 2799517757: Downloading dataset from Kaggle: arashnic/book-recommendation-dataset]
[2025-06-17 04:57:06,524: INFO: 2799517757: Downloaded dataset to: artifacts/data_ingestion/data.zip]
[2025-06-17 04:57:07,078: INFO: 2799517757: Extracted data to: artifacts/data_ingestion/data]
[2025-06-17 04:57:07,078: INFO: 2799517757: Reading data files with specified dtypes...]
[2025-06-17 04:57:08,752: ERROR: 2799517757: Error in merge_data: Unable to parse string "DK Publishing Inc" at position 12930]
Traceback (most recent call last):
  File "pandas/_libs/lib.pyx", line 2407, in pandas._libs.lib.maybe_convert_numeric
ValueError: Unable to parse string "DK Publishing Inc"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\newst\AppData\Local\Temp\ipykernel_15632\2799517757.py", line 80, in merge_data
    books_df = pd.read_csv(
               ^^^^^^^^^^^^
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\io\parsers\readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\io\parsers\readers.py", line 626, in _read
    return parser.read(nrows)
           ^^^^^^^^^^^^^^^^^^
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\io\parsers\readers.py", line 1923, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\io\parsers\c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pandas/_libs/parsers.pyx", line 838, in pandas._libs.parsers.TextReader.read_low_memory
  File "pandas/_libs/parsers.pyx", line 921, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 1066, in pandas._libs.parsers.TextReader._convert_column_data
  File "pandas/_libs/parsers.pyx", line 1105, in pandas._libs.parsers.TextReader._convert_tokens
  File "pandas/_libs/parsers.pyx", line 1211, in pandas._libs.parsers.TextReader._convert_with_dtype
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\core\arrays\numeric.py", line 283, in _from_sequence_of_strings
    scalars = to_numeric(strings, errors="raise", dtype_backend="numpy_nullable")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\core\tools\numeric.py", line 235, in to_numeric
    values, new_mask = lib.maybe_convert_numeric(  # type: ignore[call-overload]
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pandas/_libs/lib.pyx", line 2449, in pandas._libs.lib.maybe_convert_numeric
ValueError: Unable to parse string "DK Publishing Inc" at position 12930
[2025-06-17 05:03:05,253: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-17 05:03:05,260: INFO: common: created directory at: artifacts]
[2025-06-17 05:03:05,261: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-17 05:03:05,261: INFO: 3081445773: File already exists of size: ~ 24903 KB]
[2025-06-17 05:03:05,869: INFO: 3081445773: Extracted data to: artifacts/data_ingestion/data]
[2025-06-17 05:07:27,091: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-17 05:07:27,093: INFO: common: created directory at: artifacts]
[2025-06-17 05:07:27,095: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-17 05:07:27,095: INFO: 3955689425: File already exists of size: ~ 24903 KB]
[2025-06-17 05:07:27,686: INFO: 3955689425: Extracted data to: artifacts/data_ingestion/data]
[2025-06-17 05:09:33,395: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-17 05:09:33,402: INFO: common: created directory at: artifacts]
[2025-06-17 05:09:33,405: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-17 05:09:33,405: INFO: 3730285608: File already exists of size: ~ 24903 KB]
[2025-06-17 05:09:34,086: INFO: 3730285608: Extracted data to: artifacts/data_ingestion/data]
[2025-06-17 05:11:06,631: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-17 05:11:06,639: INFO: common: created directory at: artifacts]
[2025-06-17 05:11:06,639: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-17 05:11:06,639: INFO: 381861995: File already exists of size: ~ 24903 KB]
[2025-06-17 05:11:07,226: INFO: 381861995: Extracted data to: artifacts/data_ingestion/data]
[2025-06-17 05:11:07,226: INFO: 381861995: Reading books data from: artifacts/data_ingestion/data\Books.csv]
[2025-06-17 05:14:02,825: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-17 05:14:02,833: INFO: common: created directory at: artifacts]
[2025-06-17 05:14:02,833: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-17 05:14:02,833: INFO: 2408275676: File already exists of size: ~ 24903 KB]
[2025-06-17 05:14:03,451: INFO: 2408275676: Extracted data to: artifacts/data_ingestion/data]
[2025-06-17 05:14:03,451: INFO: 2408275676: Reading books data from: artifacts/data_ingestion/data\Books.csv]
[2025-06-17 05:15:35,196: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-17 05:15:35,196: INFO: common: created directory at: artifacts]
[2025-06-17 05:15:35,204: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-17 05:15:35,204: INFO: 2759669161: File already exists of size: ~ 24903 KB]
[2025-06-17 05:15:35,738: INFO: 2759669161: Extracted data to: artifacts/data_ingestion/data]
[2025-06-17 05:15:35,738: INFO: 2759669161: Reading books data from: artifacts/data_ingestion/data\Books.csv]
[2025-06-17 05:15:37,999: INFO: 2759669161: Reading data files with specified dtypes...]
[2025-06-17 05:15:42,821: ERROR: 2759669161: Error in merge_data: cannot safely cast non-equivalent float64 to int8]
Traceback (most recent call last):
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\core\arrays\integer.py", line 53, in _safe_cast
    return values.astype(dtype, casting="safe", copy=copy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Cannot cast array data from dtype('float64') to dtype('int8') according to the rule 'safe'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\newst\AppData\Local\Temp\ipykernel_17304\2759669161.py", line 142, in merge_data
    users_df = pd.read_csv(
               ^^^^^^^^^^^^
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\io\parsers\readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\io\parsers\readers.py", line 626, in _read
    return parser.read(nrows)
           ^^^^^^^^^^^^^^^^^^
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\io\parsers\readers.py", line 1923, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\io\parsers\c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pandas/_libs/parsers.pyx", line 838, in pandas._libs.parsers.TextReader.read_low_memory
  File "pandas/_libs/parsers.pyx", line 921, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 1066, in pandas._libs.parsers.TextReader._convert_column_data
  File "pandas/_libs/parsers.pyx", line 1105, in pandas._libs.parsers.TextReader._convert_tokens
  File "pandas/_libs/parsers.pyx", line 1211, in pandas._libs.parsers.TextReader._convert_with_dtype
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\core\arrays\numeric.py", line 284, in _from_sequence_of_strings
    return cls._from_sequence(scalars, dtype=dtype, copy=copy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\core\arrays\masked.py", line 153, in _from_sequence
    values, mask = cls._coerce_to_array(scalars, dtype=dtype, copy=copy)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\core\arrays\numeric.py", line 272, in _coerce_to_array
    values, mask, _, _ = _coerce_to_data_and_mask(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\core\arrays\numeric.py", line 229, in _coerce_to_data_and_mask
    values = dtype_cls._safe_cast(values, dtype, copy=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\core\arrays\integer.py", line 59, in _safe_cast
    raise TypeError(
TypeError: cannot safely cast non-equivalent float64 to int8
[2025-06-17 05:16:44,262: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-17 05:16:44,262: INFO: common: created directory at: artifacts]
[2025-06-17 05:16:44,270: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-17 05:16:44,270: INFO: 3946546995: File already exists of size: ~ 24903 KB]
[2025-06-17 05:16:44,829: INFO: 3946546995: Extracted data to: artifacts/data_ingestion/data]
[2025-06-17 05:17:18,131: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-17 05:17:18,131: INFO: common: created directory at: artifacts]
[2025-06-17 05:17:18,131: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-17 05:17:18,141: INFO: 3946546995: File already exists of size: ~ 24903 KB]
[2025-06-17 05:17:18,811: INFO: 3946546995: Extracted data to: artifacts/data_ingestion/data]
[2025-06-17 05:17:18,811: INFO: 3946546995: Reading data files with specified dtypes...]
[2025-06-17 05:17:23,590: ERROR: 3946546995: Error in merge_data: cannot safely cast non-equivalent float64 to int8]
Traceback (most recent call last):
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\core\arrays\integer.py", line 53, in _safe_cast
    return values.astype(dtype, casting="safe", copy=copy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Cannot cast array data from dtype('float64') to dtype('int8') according to the rule 'safe'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\newst\AppData\Local\Temp\ipykernel_18664\3946546995.py", line 92, in merge_data
    users_df = pd.read_csv(
               ^^^^^^^^^^^^
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\io\parsers\readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\io\parsers\readers.py", line 626, in _read
    return parser.read(nrows)
           ^^^^^^^^^^^^^^^^^^
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\io\parsers\readers.py", line 1923, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\io\parsers\c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pandas/_libs/parsers.pyx", line 838, in pandas._libs.parsers.TextReader.read_low_memory
  File "pandas/_libs/parsers.pyx", line 921, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 1066, in pandas._libs.parsers.TextReader._convert_column_data
  File "pandas/_libs/parsers.pyx", line 1105, in pandas._libs.parsers.TextReader._convert_tokens
  File "pandas/_libs/parsers.pyx", line 1211, in pandas._libs.parsers.TextReader._convert_with_dtype
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\core\arrays\numeric.py", line 284, in _from_sequence_of_strings
    return cls._from_sequence(scalars, dtype=dtype, copy=copy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\core\arrays\masked.py", line 153, in _from_sequence
    values, mask = cls._coerce_to_array(scalars, dtype=dtype, copy=copy)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\core\arrays\numeric.py", line 272, in _coerce_to_array
    values, mask, _, _ = _coerce_to_data_and_mask(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\core\arrays\numeric.py", line 229, in _coerce_to_data_and_mask
    values = dtype_cls._safe_cast(values, dtype, copy=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\core\arrays\integer.py", line 59, in _safe_cast
    raise TypeError(
TypeError: cannot safely cast non-equivalent float64 to int8
[2025-06-17 05:18:15,617: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-17 05:18:15,617: INFO: common: created directory at: artifacts]
[2025-06-17 05:18:15,625: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-17 05:18:15,625: INFO: 2255970579: File already exists of size: ~ 24903 KB]
[2025-06-17 05:18:16,167: INFO: 2255970579: Extracted data to: artifacts/data_ingestion/data]
[2025-06-17 05:18:16,167: INFO: 2255970579: Reading data files with specified dtypes...]
[2025-06-17 05:18:20,227: INFO: 2255970579: Cleaning data...]
[2025-06-17 05:18:20,284: ERROR: 2255970579: Error in merge_data: '>=' not supported between instances of 'str' and 'int']
Traceback (most recent call last):
  File "C:\Users\newst\AppData\Local\Temp\ipykernel_20800\2255970579.py", line 101, in merge_data
    books_df['Year-Of-Publication'] = books_df['Year-Of-Publication'].clip(
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\core\generic.py", line 9117, in clip
    return self._clip_with_scalar(lower, upper, inplace=inplace)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\core\generic.py", line 8857, in _clip_with_scalar
    cond = mask | (self >= lower)
                   ^^^^^^^^^^^^^
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\core\ops\common.py", line 76, in new_method
    return method(self, other)
           ^^^^^^^^^^^^^^^^^^^
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\core\arraylike.py", line 60, in __ge__
    return self._cmp_method(other, operator.ge)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\core\series.py", line 6130, in _cmp_method
    res_values = ops.comparison_op(lvalues, rvalues, op)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\core\ops\array_ops.py", line 344, in comparison_op
    res_values = comp_method_OBJECT_ARRAY(op, lvalues, rvalues)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\core\ops\array_ops.py", line 129, in comp_method_OBJECT_ARRAY
    result = libops.scalar_compare(x.ravel(), y, op)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pandas/_libs/ops.pyx", line 107, in pandas._libs.ops.scalar_compare
TypeError: '>=' not supported between instances of 'str' and 'int'
[2025-06-17 05:21:45,905: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-17 05:21:45,905: INFO: common: created directory at: artifacts]
[2025-06-17 05:21:45,905: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-17 05:21:45,905: INFO: 4170389737: File already exists of size: ~ 24903 KB]
[2025-06-17 05:21:46,654: INFO: 4170389737: Extracted data to: artifacts/data_ingestion/data]
[2025-06-17 05:21:46,654: INFO: 4170389737: Reading data files with specified dtypes...]
[2025-06-17 05:21:51,221: INFO: 4170389737: Cleaning data...]
[2025-06-17 05:21:51,237: ERROR: 4170389737: Error in merge_data: '>=' not supported between instances of 'str' and 'int']
Traceback (most recent call last):
  File "C:\Users\newst\AppData\Local\Temp\ipykernel_19956\4170389737.py", line 101, in merge_data
    books_df['Year-Of-Publication'] = books_df['Year-Of-Publication'].clip(
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\core\generic.py", line 9117, in clip
    return self._clip_with_scalar(lower, upper, inplace=inplace)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\core\generic.py", line 8857, in _clip_with_scalar
    cond = mask | (self >= lower)
                   ^^^^^^^^^^^^^
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\core\ops\common.py", line 76, in new_method
    return method(self, other)
           ^^^^^^^^^^^^^^^^^^^
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\core\arraylike.py", line 60, in __ge__
    return self._cmp_method(other, operator.ge)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\core\series.py", line 6130, in _cmp_method
    res_values = ops.comparison_op(lvalues, rvalues, op)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\core\ops\array_ops.py", line 344, in comparison_op
    res_values = comp_method_OBJECT_ARRAY(op, lvalues, rvalues)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\core\ops\array_ops.py", line 129, in comp_method_OBJECT_ARRAY
    result = libops.scalar_compare(x.ravel(), y, op)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pandas/_libs/ops.pyx", line 107, in pandas._libs.ops.scalar_compare
TypeError: '>=' not supported between instances of 'str' and 'int'
[2025-06-17 05:26:21,394: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-17 05:26:21,394: INFO: common: created directory at: artifacts]
[2025-06-17 05:26:21,394: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-17 05:26:21,394: INFO: 2066201408: File already exists of size: ~ 24903 KB]
[2025-06-17 05:26:22,031: INFO: 2066201408: Extracted data to: artifacts/data_ingestion/data]
[2025-06-17 05:26:22,031: INFO: 2066201408: Reading data files with specified dtypes...]
[2025-06-17 05:26:26,447: INFO: 2066201408: Cleaning data...]
[2025-06-17 05:26:26,721: WARNING: 2066201408: Cleaned 3 invalid publication years]
[2025-06-17 05:26:26,737: ERROR: 2066201408: Error in merge_data: '>=' not supported between instances of 'str' and 'int']
Traceback (most recent call last):
  File "C:\Users\newst\AppData\Local\Temp\ipykernel_13676\2066201408.py", line 119, in merge_data
    users_df['Age'] = users_df['Age'].clip(
                      ^^^^^^^^^^^^^^^^^^^^^
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\core\generic.py", line 9117, in clip
    return self._clip_with_scalar(lower, upper, inplace=inplace)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\core\generic.py", line 8857, in _clip_with_scalar
    cond = mask | (self >= lower)
                   ^^^^^^^^^^^^^
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\core\ops\common.py", line 76, in new_method
    return method(self, other)
           ^^^^^^^^^^^^^^^^^^^
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\core\arraylike.py", line 60, in __ge__
    return self._cmp_method(other, operator.ge)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\core\series.py", line 6130, in _cmp_method
    res_values = ops.comparison_op(lvalues, rvalues, op)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\core\ops\array_ops.py", line 344, in comparison_op
    res_values = comp_method_OBJECT_ARRAY(op, lvalues, rvalues)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\core\ops\array_ops.py", line 129, in comp_method_OBJECT_ARRAY
    result = libops.scalar_compare(x.ravel(), y, op)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pandas/_libs/ops.pyx", line 107, in pandas._libs.ops.scalar_compare
TypeError: '>=' not supported between instances of 'str' and 'int'
[2025-06-17 05:31:02,416: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-17 05:31:02,416: INFO: common: created directory at: artifacts]
[2025-06-17 05:31:02,416: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-17 05:31:02,424: INFO: 1739755337: File already exists of size: ~ 24903 KB]
[2025-06-17 05:31:03,091: INFO: 1739755337: Extracted data to: artifacts/data_ingestion/data]
[2025-06-17 05:31:03,091: INFO: 1739755337: Reading data files with specified dtypes...]
[2025-06-17 05:31:07,382: INFO: 1739755337: Cleaning data...]
[2025-06-17 05:31:07,609: WARNING: 1739755337: Cleaned 3 invalid publication years]
[2025-06-17 05:31:08,129: INFO: 1739755337: Merging datasets...]
[2025-06-17 05:31:09,834: ERROR: 1739755337: Error in merge_data: Merge keys are not unique in right dataset; not a many-to-one merge]
Traceback (most recent call last):
  File "C:\Users\newst\AppData\Local\Temp\ipykernel_5688\1739755337.py", line 131, in merge_data
    book_ratings = pd.merge(
                   ^^^^^^^^^
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\core\reshape\merge.py", line 170, in merge
    op = _MergeOperation(
         ^^^^^^^^^^^^^^^^
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\core\reshape\merge.py", line 813, in __init__
    self._validate_validate_kwd(validate)
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\core\reshape\merge.py", line 1669, in _validate_validate_kwd
    raise MergeError(
pandas.errors.MergeError: Merge keys are not unique in right dataset; not a many-to-one merge
[2025-06-17 05:34:16,782: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-17 05:34:16,790: INFO: common: created directory at: artifacts]
[2025-06-17 05:34:16,790: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-17 05:34:16,790: INFO: 3266401565: File already exists of size: ~ 24903 KB]
[2025-06-17 05:34:17,385: INFO: 3266401565: Extracted data to: artifacts/data_ingestion/data]
[2025-06-17 05:34:17,385: INFO: 3266401565: Reading data files with specified dtypes...]
[2025-06-17 05:34:21,654: INFO: 3266401565: Cleaning data...]
[2025-06-17 05:34:22,719: INFO: 3266401565: Removed 0 duplicate books]
[2025-06-17 05:34:22,719: INFO: 3266401565: Merging datasets...]
[2025-06-17 05:34:26,541: INFO: 3266401565: Final merged dataset shape: (1031139, 11)]
[2025-06-17 05:34:35,105: INFO: 3266401565: Saved cleaned merged data to artifacts/data_ingestion\merged_data.csv]
[2025-06-17 05:35:06,031: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-17 05:35:06,031: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-17 05:35:06,062: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-17 05:35:06,062: INFO: common: created directory at: artifacts]
[2025-06-17 05:35:06,062: INFO: common: created directory at: artifacts/data_validation]
[2025-06-17 05:42:44,815: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-17 05:42:44,823: INFO: common: created directory at: artifacts]
[2025-06-17 05:42:44,823: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-17 05:42:44,823: INFO: 4073022898: Downloading dataset from Kaggle: arashnic/book-recommendation-dataset]
[2025-06-17 05:42:49,113: INFO: 4073022898: Downloaded dataset to: artifacts/data_ingestion/data.zip]
[2025-06-17 05:42:49,730: INFO: 4073022898: Extracted data to: artifacts/data_ingestion/data]
[2025-06-17 05:42:49,730: INFO: 4073022898: Reading data files with specified dtypes...]
[2025-06-17 05:42:53,809: INFO: 4073022898: Cleaning data...]
[2025-06-17 05:42:54,923: INFO: 4073022898: Removed 0 duplicate books]
[2025-06-17 05:42:54,924: INFO: 4073022898: Merging datasets...]
[2025-06-17 05:42:57,374: ERROR: 4073022898: Error in merge_data: You are trying to merge on Int32 and object columns for key 'User-ID'. If you wish to proceed you should use pd.concat]
Traceback (most recent call last):
  File "C:\Users\newst\AppData\Local\Temp\ipykernel_6380\4073022898.py", line 136, in merge_data
    final_df = pd.merge(
               ^^^^^^^^^
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\core\reshape\merge.py", line 170, in merge
    op = _MergeOperation(
         ^^^^^^^^^^^^^^^^
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\core\reshape\merge.py", line 807, in __init__
    self._maybe_coerce_merge_keys()
  File "d:\newst\miniconda3\envs\recommendation-engine-env\Lib\site-packages\pandas\core\reshape\merge.py", line 1508, in _maybe_coerce_merge_keys
    raise ValueError(msg)
ValueError: You are trying to merge on Int32 and object columns for key 'User-ID'. If you wish to proceed you should use pd.concat
[2025-06-17 05:43:51,801: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-17 05:43:51,801: INFO: common: created directory at: artifacts]
[2025-06-17 05:43:51,805: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-17 05:43:51,805: INFO: 3266401565: Downloading dataset from Kaggle: arashnic/book-recommendation-dataset]
[2025-06-17 05:44:16,830: INFO: 3266401565: Downloaded dataset to: artifacts/data_ingestion/data.zip]
[2025-06-17 05:44:17,454: INFO: 3266401565: Extracted data to: artifacts/data_ingestion/data]
[2025-06-17 05:44:17,454: INFO: 3266401565: Reading data files with specified dtypes...]
[2025-06-17 05:44:21,728: INFO: 3266401565: Cleaning data...]
[2025-06-17 05:44:22,811: INFO: 3266401565: Removed 0 duplicate books]
[2025-06-17 05:44:22,811: INFO: 3266401565: Merging datasets...]
[2025-06-17 05:44:26,353: INFO: 3266401565: Final merged dataset shape: (1031139, 11)]
[2025-06-17 05:44:34,159: INFO: 3266401565: Saved cleaned merged data to artifacts/data_ingestion\merged_data.csv]
[2025-06-17 05:45:25,206: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-17 05:45:25,210: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-17 05:45:25,220: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-17 05:45:25,220: INFO: common: created directory at: artifacts]
[2025-06-17 05:45:25,220: INFO: common: created directory at: artifacts/data_validation]
[2025-06-17 05:48:47,814: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-17 05:48:47,821: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-17 05:48:47,823: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-17 05:48:47,833: INFO: common: created directory at: artifacts]
[2025-06-17 05:48:47,833: INFO: common: created directory at: artifacts/data_transformation]
[2025-06-17 05:49:06,889: INFO: 2148425976: Splited data into training and test sets]
[2025-06-17 05:49:06,889: INFO: 2148425976: (773354, 11)]
[2025-06-17 05:49:06,889: INFO: 2148425976: (257785, 11)]
[2025-06-17 06:10:09,038: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-17 06:10:09,040: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-17 06:10:09,045: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-17 06:10:09,046: INFO: common: created directory at: artifacts]
[2025-06-17 06:10:09,054: ERROR: 1711784427: Error in training hybrid recommender]
Traceback (most recent call last):
  File "box\\box.py", line 594, in box.box.Box.__getitem__
KeyError: 'hybrid_recommender'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\\box.py", line 633, in box.box.Box.__getattr__
  File "box\\box.py", line 621, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'hybrid_recommender'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\\box.py", line 635, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'hybrid_recommender'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\\config_box.py", line 29, in box.config_box.ConfigBox.__getattr__
  File "box\\box.py", line 649, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'hybrid_recommender'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\\box.py", line 594, in box.box.Box.__getitem__
KeyError: 'hybrid_recommender'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\\box.py", line 633, in box.box.Box.__getattr__
  File "box\\box.py", line 621, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'hybrid_recommender'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\\box.py", line 635, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'hybrid_recommender'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\newst\AppData\Local\Temp\ipykernel_10832\1711784427.py", line 3, in <module>
    recommender_config = config.get_hybrid_recommender_config()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\newst\AppData\Local\Temp\ipykernel_10832\3614958655.py", line 15, in get_hybrid_recommender_config
    config = self.config.hybrid_recommender
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "box\\config_box.py", line 31, in box.config_box.ConfigBox.__getattr__
  File "box\\box.py", line 649, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'hybrid_recommender'"
[2025-06-17 06:17:11,999: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-17 06:17:12,008: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-17 06:17:12,011: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-17 06:17:12,012: INFO: common: created directory at: artifacts]
[2025-06-17 06:17:12,012: ERROR: 1711784427: Error in training hybrid recommender]
Traceback (most recent call last):
  File "C:\Users\newst\AppData\Local\Temp\ipykernel_6496\1711784427.py", line 3, in <module>
    recommender_config = config.get_hybrid_recommender_config()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigurationManager' object has no attribute 'get_hybrid_recommender_config'
[2025-06-17 06:18:08,873: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-17 06:18:08,882: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-17 06:18:08,885: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-17 06:18:08,886: INFO: common: created directory at: artifacts]
[2025-06-17 06:18:08,887: INFO: common: created directory at: artifacts/model_trainer]
[2025-06-17 06:18:13,370: ERROR: 1169397994: Error in training hybrid recommender]
Traceback (most recent call last):
  File "C:\Users\newst\AppData\Local\Temp\ipykernel_12492\1169397994.py", line 5, in <module>
    recommender.train()
  File "C:\Users\newst\AppData\Local\Temp\ipykernel_12492\2461798883.py", line 76, in train
    user_items = coo_matrix(
                 ^^^^^^^^^^
NameError: name 'coo_matrix' is not defined
[2025-06-17 06:21:36,164: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-17 06:21:36,166: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-17 06:21:36,166: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-17 06:21:36,166: INFO: common: created directory at: artifacts]
[2025-06-17 06:21:36,171: INFO: common: created directory at: artifacts/model_trainer]
[2025-06-17 06:21:40,506: INFO: 1614537693: Training implicit ALS model...]
[2025-06-17 06:21:46,308: INFO: 1614537693: Training neural network hybrid model...]
[2025-06-18 14:55:49,432: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-18 14:55:49,547: INFO: common: created directory at: artifacts]
[2025-06-18 14:55:49,547: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-18 14:56:10,798: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-18 14:56:10,799: INFO: common: created directory at: artifacts]
[2025-06-18 14:56:10,799: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-18 14:56:10,799: INFO: 1947799409: Generating data to: artifacts/data_ingestion/generated_data]
[2025-06-18 14:57:32,954: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-18 14:57:32,954: INFO: common: created directory at: artifacts]
[2025-06-18 14:57:32,954: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-18 14:57:32,954: INFO: 1772966207: Generating data to: artifacts/data_ingestion/generated_data]
[2025-06-18 14:57:36,200: INFO: 1772966207: Generated bookings.csv, comments.csv, and likes.csv with 100,000 rows each.]
[2025-06-19 09:33:50,222: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-19 09:33:50,246: INFO: common: created directory at: artifacts]
[2025-06-19 09:33:50,248: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-19 09:33:50,251: INFO: 531171295: Generating data to: artifacts/data_ingestion/generated_data]
[2025-06-19 09:33:53,761: INFO: 531171295: Generated bookings.csv, comments.csv, and likes.csv with 100,000 rows each.]
[2025-06-30 09:48:19,904: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-30 09:48:19,919: INFO: common: created directory at: artifacts]
[2025-06-30 09:48:19,923: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-30 09:48:19,923: INFO: 531171295: Generating data to: artifacts/data_ingestion/generated_data]
[2025-06-30 09:48:23,237: INFO: 531171295: Generated bookings.csv, comments.csv, and likes.csv with 100,000 rows each.]
[2025-06-30 11:48:28,667: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-30 11:48:28,667: INFO: common: created directory at: artifacts]
[2025-06-30 11:48:28,675: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-30 11:48:28,676: INFO: 3537254787: Generating data to: artifacts/data_ingestion/generated_data]
[2025-06-30 11:48:30,766: INFO: 3537254787: Generated bookings.csv, comments.csv, and likes.csv with 100,000 rows each.]
[2025-06-30 11:48:30,766: INFO: 3537254787: Added 20000 overlapping user-event pairs across all datasets.]
[2025-06-30 11:54:59,648: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-30 11:54:59,650: INFO: common: created directory at: artifacts]
[2025-06-30 11:54:59,651: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-30 11:54:59,652: INFO: 183717319: Generating data to: artifacts/data_ingestion/generated_data]
[2025-06-30 12:08:02,570: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-30 12:08:02,571: INFO: common: created directory at: artifacts]
[2025-06-30 12:08:02,572: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-30 12:08:02,573: INFO: 1829231883: Files already exist in: artifacts/data_ingestion/generated_data]
[2025-06-30 12:08:15,070: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-30 12:08:15,072: INFO: common: created directory at: artifacts]
[2025-06-30 12:08:15,074: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-30 12:08:15,075: INFO: 1829231883: Generating data to: artifacts/data_ingestion/generated_data]
[2025-06-30 12:08:17,315: INFO: 1829231883: Generated files with 100000 bookings, 100000 comments, and 100000 likes]
[2025-06-30 15:22:05,622: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-30 15:22:05,622: INFO: common: created directory at: artifacts]
[2025-06-30 15:22:05,622: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-30 15:22:05,622: INFO: 964962886: Generating enhanced data to: artifacts/data_ingestion/generated_data]
[2025-06-30 15:22:09,197: INFO: 964962886: Generated enhanced datasets with:]
[2025-06-30 15:22:09,197: INFO: 964962886: - Bookings: 150000 (Target: 150000)]
[2025-06-30 15:22:09,197: INFO: 964962886: - Comments: 245397 (Target: 200000)]
[2025-06-30 15:22:09,197: INFO: 964962886: - Likes: 145397]
[2025-06-30 15:22:09,197: INFO: 964962886: - Full interactions: 30000 events]
[2025-06-30 15:38:25,292: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-30 15:38:25,292: INFO: common: created directory at: artifacts]
[2025-06-30 15:38:25,292: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-30 15:38:25,555: INFO: 964962886: Generating enhanced data to: artifacts/data_ingestion/generated_data]
[2025-06-30 15:38:29,668: INFO: 964962886: Generated enhanced datasets with:]
[2025-06-30 15:38:29,668: INFO: 964962886: - Bookings: 150000 (Target: 150000)]
[2025-06-30 15:38:29,668: INFO: 964962886: - Comments: 245397 (Target: 200000)]
[2025-06-30 15:38:29,668: INFO: 964962886: - Likes: 145397]
[2025-06-30 15:38:29,668: INFO: 964962886: - Full interactions: 30000 events]
[2025-06-30 15:46:00,392: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-30 15:46:00,392: INFO: common: created directory at: artifacts]
[2025-06-30 15:46:00,392: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-30 15:55:40,720: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-30 15:55:40,720: INFO: common: created directory at: artifacts]
[2025-06-30 15:55:40,731: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-30 15:58:02,749: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-30 15:58:02,751: INFO: common: created directory at: artifacts]
[2025-06-30 15:58:02,752: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-30 15:58:02,753: INFO: 964962886: Generating enhanced data to: artifacts/data_ingestion/generated_data]
[2025-06-30 15:58:06,200: INFO: 964962886: Generated enhanced datasets with:]
[2025-06-30 15:58:06,201: INFO: 964962886: - Bookings: 150000 (Target: 150000)]
[2025-06-30 15:58:06,201: INFO: 964962886: - Comments: 245397 (Target: 200000)]
[2025-06-30 15:58:06,201: INFO: 964962886: - Likes: 145397]
[2025-06-30 15:58:06,201: INFO: 964962886: - Full interactions: 30000 events]
[2025-06-30 15:58:19,333: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-30 15:58:19,344: INFO: common: created directory at: artifacts]
[2025-06-30 15:58:19,345: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-30 15:58:19,347: INFO: 964962886: Generating enhanced data to: artifacts/data_ingestion/generated_data]
[2025-06-30 15:58:22,780: INFO: 964962886: Generated enhanced datasets with:]
[2025-06-30 15:58:22,780: INFO: 964962886: - Bookings: 150000 (Target: 150000)]
[2025-06-30 15:58:22,780: INFO: 964962886: - Comments: 245397 (Target: 200000)]
[2025-06-30 15:58:22,780: INFO: 964962886: - Likes: 145397]
[2025-06-30 15:58:22,780: INFO: 964962886: - Full interactions: 30000 events]
[2025-06-30 16:09:50,323: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-30 16:09:50,327: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-30 16:09:50,328: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-30 16:09:50,410: INFO: common: created directory at: artifacts]
[2025-06-30 16:09:50,417: INFO: common: created directory at: artifacts/data_validation]
[2025-06-30 16:11:32,318: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-30 16:11:32,318: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-30 16:11:32,322: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-30 16:11:32,323: INFO: common: created directory at: artifacts]
[2025-06-30 16:11:32,324: INFO: common: created directory at: artifacts/data_validation]
[2025-06-30 16:19:05,503: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-30 16:19:05,511: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-30 16:19:05,513: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-30 16:19:05,515: INFO: common: created directory at: artifacts]
[2025-06-30 16:19:05,516: INFO: common: created directory at: artifacts/data_validation]
[2025-06-30 16:28:12,563: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-30 16:28:12,567: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-30 16:28:12,577: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-30 16:28:12,578: INFO: common: created directory at: artifacts]
[2025-06-30 16:28:12,580: INFO: common: created directory at: artifacts/data_validation]
[2025-06-30 16:29:00,940: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-30 16:29:00,942: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-30 16:29:00,944: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-30 16:29:00,945: INFO: common: created directory at: artifacts]
[2025-06-30 16:29:00,945: INFO: common: created directory at: artifacts/data_validation]
[2025-06-30 16:32:29,831: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-30 16:32:29,831: INFO: common: created directory at: artifacts]
[2025-06-30 16:32:29,831: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-30 16:32:29,831: INFO: 964962886: Generating enhanced data to: artifacts/data_ingestion/generated_data]
[2025-06-30 16:32:33,329: INFO: 964962886: Generated enhanced datasets with:]
[2025-06-30 16:32:33,329: INFO: 964962886: - Bookings: 150000 (Target: 150000)]
[2025-06-30 16:32:33,329: INFO: 964962886: - Comments: 245397 (Target: 200000)]
[2025-06-30 16:32:33,329: INFO: 964962886: - Likes: 145397]
[2025-06-30 16:32:33,329: INFO: 964962886: - Full interactions: 30000 events]
[2025-06-30 16:34:28,467: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-30 16:34:28,470: INFO: common: created directory at: artifacts]
[2025-06-30 16:34:28,471: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-30 16:34:28,471: INFO: 964962886: Files already exist in: artifacts/data_ingestion/generated_data]
[2025-06-30 16:35:08,149: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-30 16:35:08,149: INFO: common: created directory at: artifacts]
[2025-06-30 16:35:08,149: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-30 16:35:08,154: INFO: 964962886: Generating enhanced data to: artifacts/data_ingestion/generated_data]
[2025-06-30 16:35:13,807: INFO: 964962886: Generated enhanced datasets with:]
[2025-06-30 16:35:13,807: INFO: 964962886: - Bookings: 150000 (Target: 150000)]
[2025-06-30 16:35:13,807: INFO: 964962886: - Comments: 245397 (Target: 200000)]
[2025-06-30 16:35:13,807: INFO: 964962886: - Likes: 145397]
[2025-06-30 16:35:13,820: INFO: 964962886: - Full interactions: 30000 events]
[2025-06-30 16:36:20,790: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-30 16:36:20,790: INFO: common: created directory at: artifacts]
[2025-06-30 16:36:20,790: INFO: common: created directory at: artifacts/data_ingestion]
[2025-06-30 16:36:20,798: INFO: 964962886: Generating enhanced data to: artifacts/data_ingestion/generated_data]
[2025-06-30 16:36:25,665: INFO: 964962886: Generated enhanced datasets with:]
[2025-06-30 16:36:25,665: INFO: 964962886: - Bookings: 150000 (Target: 150000)]
[2025-06-30 16:36:25,665: INFO: 964962886: - Comments: 245397 (Target: 200000)]
[2025-06-30 16:36:25,665: INFO: 964962886: - Likes: 145397]
[2025-06-30 16:36:25,665: INFO: 964962886: - Full interactions: 30000 events]
[2025-06-30 16:37:13,991: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-30 16:37:13,996: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-30 16:37:13,996: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-30 16:37:13,996: INFO: common: created directory at: artifacts]
[2025-06-30 16:37:13,996: INFO: common: created directory at: artifacts/data_validation]
[2025-06-30 16:42:44,811: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-06-30 16:42:44,816: INFO: common: yaml file: params.yaml loaded successfully]
[2025-06-30 16:42:44,816: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-06-30 16:42:44,816: INFO: common: created directory at: artifacts]
[2025-06-30 16:42:44,816: INFO: common: created directory at: artifacts/data_transformation]
[2025-06-30 16:42:47,060: INFO: 2148425976: Splited data into training and test sets]
[2025-06-30 16:42:47,061: INFO: 2148425976: (150000, 9)]
[2025-06-30 16:42:47,061: INFO: 2148425976: (50000, 9)]
